### ISSUE TITLE
지워지지가 않습니다. 

### ISSUE THREAD

**Issue by midduck** [asbubam/hello-node#1]
쿠버네티스 코드를 연습하면서 샘플 제작으로 현재 이 예제를 사용하였습니다.

근데 계속해서 남아 있는게 문제가 됩니다.  

 쿠버네티스 자체적으로 프로젝트도 그렇고 지우고 다시 생성했고, 몇번이고 다시 컴퓨터 재부팅을 했지만 

도커 for windows 를 키기만 하면 http://localhost:8080 에 남아있습니다. 포트가 계속해서 할당되어 있어 다른 작업을 하질 못하네요 ㅠㅠ

**Comment by midduck** [comment]
도커 쿠버네티스와 GCP 간의 연동(싱크) 문제였습니다.

**Comment by asbubam-w** [comment]
해결되어 다행이네요. :)
